# Generated by Django 3.2.6 on 2021-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predictionresults_prediction_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresults',
            name='city_dev_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresults',
            name='last_new_job',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresults',
            name='training_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionresults',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
