# Generated by Django 3.2.6 on 2021-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20210811_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresults',
            name='experience',
            field=models.CharField(choices=[('Has relevent experience', 'Has relevent experience'), ('No relevent experience', 'No relevent experience')], default='No relevent experience', max_length=30),
        ),
    ]
