# Generated by Django 3.2.6 on 2021-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20210811_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresults',
            name='company_size',
            field=models.CharField(choices=[('<10', 'less than 10'), ('10/49', '10 to 49'), ('50-99', '50 to 99'), ('100-500', '100 to 500'), ('500-999', '500 to 999'), ('1000-4999', '1000 to 4999'), ('5000-9999', '5000 to 9999'), ('10000+', 'more than 10000')], default='<10', max_length=20),
        ),
    ]
